<a href="https://colab.research.google.com/github/Wenypb/Opti_No_Lineal/blob/main/Tare_Newton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=2
b=-2
c=9
d=11
e=-9
f=6
#MATRIZ A
A = np.array([[a, b/2], [b/2, c]])
#VECTOR B
B = np.array([[d],[e]])
#C
C=np.array([f])
#Vector inicial
x0=np.array([[1],[1]])
#Gradiente x0
g= (2*A)@x0+B
print(g)
#Hessiana x0
H= (2*A)
H_inv=np.linalg.inv(H)
print(H_inv)
print(H_inv@g)
x1=x0-(H_inv@g)
print(x1)

[[13.]
 [ 7.]]
[[0.26470588 0.02941176]
 [0.02941176 0.05882353]]
[[3.64705882]
 [0.79411765]]
[[-2.64705882]
 [ 0.20588235]]


In [14]:

import numpy as np
import math as ma

def funcion(x):
  return 10*(x[1]-x[0]**2)**2+(1-x[0])**2

def gradiente(x):
  g = np.empty((2,1))
  g[0] = (-40*x[0]*x[1]+40*(x[0]**3)+2*x[0]-2)
  g[1] = (20*x[1]-20*x[0]**2)
  return g

def Hessiana(x):
  h=np.empty((2,2))
  x=x.reshape((2))
  h[0,0] = (-40*x[1]+120*(x[0]**2)+2)
  h[0,1] = (-40*x[0])
  h[1,0] = (-40*x[0])
  h[1,1] = (20)
  return h

#Vector inicial
xk=np.array([[-1.2],[1.0]])
#Tolerancia
Tol=0.001
#Gradiente
grad=np.array(gradiente(xk))
#Norma del gradiente
nor=np.linalg.norm(grad)
#Lista de xks
xks=[xk]
#Conteo de iteracciones
while nor>Tol:
  xk_1=xk
  #Inversa de la Hessiana
  Hk_inv=np.linalg.inv(Hessiana(xk_1))
  print("Hessiana",Hessiana(xk_1))
  print("inversa",Hk_inv)
  #Gradiente
  Gk=gradiente(xk_1)
  print("g",Gk)
  #Nuevo xk
  xk=xk_1-(Hk_inv)@Gk
  print("xk",xk)
  xks.append(xk)
  #Norma del gradiente
  nor=np.linalg.norm(gradiente(xk))
  print(nor)
print("Con un total de",i,"iteracciones se llego a este vector solución:")
print("x_",i,"=",xk)


Hessiana [[134.8  48. ]
 [ 48.   20. ]]
inversa [[ 0.05102041 -0.12244898]
 [-0.12244898  0.34387755]]
g [[-25.52]
 [ -8.8 ]]
xk [[-0.9755102 ]
 [ 0.90122449]]
6.002704261912529
Hessiana [[80.1454394  39.02040816]
 [39.02040816 20.        ]]
inversa [[ 0.24901473 -0.48583281]
 [-0.48583281  0.99786974]]
g [[-5.91747996]
 [-1.00791337]]
xk [[ 0.00835207]
 [-0.96791521]]
19.43072964433473
Hessiana [[40.72497915 -0.33408261]
 [-0.33408261 20.        ]]
inversa [[0.02455832 0.00041023]
 [0.00041023 0.05000685]]
g [[ -1.65990893]
 [-19.3596993 ]]
xk [[0.05705848]
 [0.00088336]]
1.8810670816003727
Hessiana [[ 2.35534619 -2.28233915]
 [-2.28233915 20.        ]]
inversa [[0.47735144 0.05447389]
 [0.05447389 0.0562164 ]]
g [[-1.88046862]
 [-0.04744629]]
xk [[0.95728747]
 [0.10598706]]
34.93410166690582
Hessiana [[107.72843351 -38.29149881]
 [-38.29149881  20.        ]]
inversa [[0.02905584 0.05562958]
 [0.05562958 0.156507  ]]
g [[ 30.94647414]
 [-16.20824474]]
xk [[0.95976957]
 [0.92115146]]
0